### ISSUE TITLE
[proposal]Reservations support two modes: preferred or required

### ISSUE THREAD

**Issue by fjding** [koordinator-sh/koordinator#1226]
**What is your proposal**:
Reservations support two modes: preferred or required.
prefferred: means the pod selected by the reservation owner uses the Reservation resource first.
required: means the pod selected by the owner must use the Reservation resource.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by eahydra** [comment]
Yeah. Good idea.  @fjding 

It is true that some scenarios only expect resources to be allocated from Reservation. However, the actual situation will be somewhat complicated. For example, Reservation A only reserves CPU and memory, but Pod needs CPU, memory and ENI. At this time, it is still necessary to allocate resources from the nodes. Therefore, the required semantics need to be improved together. For example, Required means that when Pod and Reservation resources overlap, Reservation resources must be used, and resources other than the intersection can be allocated from the host.

Another scenario might be considered together. For example, there are multiple Reservations on a node, and the resources reserved by each Reservation do not meet the Pod's request, but the combination of each Reservation can meet the Pod's request, or the remainder of the Reservation + Node can meet the Pod's request, then at this time Do we expect Pods to use multiple Reservations or limit Pods to only one Reservation? This scenario is not well solved in the current version. By limiting a node to only one reusable Reservation with the same Owner, this problem is temporarily circumvented, but it has not been completely resolved.
I am also thinking about this issue recently. Maybe we can consider adding a strategy. For this scenario, each Reservation + the rest of the node can meet the Pod request, so that the Reservation can be used. It is equivalent to aligning according to the Pod request. But this also has a corner case: when the node is full of many small-sized Reservations that occupy the machine, and none of them can satisfy the Pod's request, then these Reservations can't be used... This leads to new requirements...
Haha, some questions about Reservation are really interesting..We can have more discussions to find some better implementations. cc @hormes @FillZpp @saintube @ZiMengSheng

**Comment by eahydra** [comment]
Regarding this issue, I have some new thoughts.
We can consider defining the resource reuse policy of Reservation in ReservationSpec or Reservation Annotation. These policies are defined as follows:
1. `None` means that there is no restriction on the policy of reserved resources, and allocated from the Reservation first, and if it is insufficient, it is allocated from the node.
2. `Restricted` means that the resources requested by the Pod overlap with the resources reserved by the Reservation, then these intersection resources can only be allocated from the Reservation, but other resources can be allocated from the node.
3. `OnlyUseReservation` means only allocate resources from the Reservation.
4. `AlignByPod` indicates that the Pod allocates resources from the Reservation first. If the remaining resources of the Reservation are insufficient, it can be allocated from the node, but it is required to strictly follow the resource specifications of the Pod. This can be used to avoid the problem that a Pod uses multiple Reservations at the same time, but It is also possible that the Reservation reserves resources successfully, but the Reservation may not be used.

Among them, `OnlyUseReservation` is the simplest, strictest and clearest;
`AlignByPod` can avoid the problem of using multiple Reservations; `None` is the current default behavior. Both `None` and `Restricted` may still cause a Pod to use multiple Reservations. We need to continue to think about better solutions to this problem.

**Comment by saintube** [comment]
> Regarding this issue, I have some new thoughts. We can consider defining the resource reuse policy of Reservation in ReservationSpec or Reservation Annotation. These policies are defined as follows:
> 
> 1. `None` means that there is no restriction on the policy of reserved resources, and allocated from the Reservation first, and if it is insufficient, it is allocated from the node.
> 2. `Restricted` means that the resources requested by the Pod overlap with the resources reserved by the Reservation, then these intersection resources can only be allocated from the Reservation, but other resources can be allocated from the node.
> 3. `OnlyUseReservation` means only allocate resources from the Reservation.
> 4. `AlignByPod` indicates that the Pod allocates resources from the Reservation first. If the remaining resources of the Reservation are insufficient, it can be allocated from the node, but it is required to strictly follow the resource specifications of the Pod. This can be used to avoid the problem that a Pod uses multiple Reservations at the same time, but It is also possible that the Reservation reserves resources successfully, but the Reservation may not be used.
> 
> Among them, `OnlyUseReservation` is the simplest, strictest and clearest; `AlignByPod` can avoid the problem of using multiple Reservations; `None` is the current default behavior. Both `None` and `Restricted` may still cause a Pod to use multiple Reservations. We need to continue to think about better solutions to this problem.
> 
> cc @hormes @FillZpp @saintube @fjding

+1
I also think the `Restricted` mode can be defined as another attribute in the Spec. Think about a new boolean field `Restricted` indicating whether the owner can allocate with the resource types (e.g. `cpu`, `memory`, `nvidia.com/gpu`) among the reserved resources. Then the policies (perhaps named as `AllocatePolicy`) we discussed above can be defined as `None`/`Default`, `ReservationOnly`, `AlignByPod`/`Single`.

**Comment by eahydra** [comment]
>  Moreover, a principle can also be derived: only one allocation strategy can exist on a node at the same time.

It can be simplified again, None/Default cannot coexist with other strategies
