### ISSUE TITLE
[proposal] Add multiple aggregation types to nodemetric

### ISSUE THREAD

**Issue by zwForrest** [koordinator-sh/koordinator#1480]
**What is your proposal**:
Add multiple aggregation types (such as percentile / avg / min...) to nodemetric, and allow users to configure which types of aggregation to display in nodemetric. Otherwise, the default aggregation types will be used.

**Why is this needed**:
Users can choose the appropriate resource aggregation types based on their service needs.

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
As we discussed, before we imports more aggregation types, we need to clarify what does these metrics used for. If it is just used for tuning during load aware optimization, this will imports too much details.
Actually, instead of extremely accurate, relatively conservative metrics such as p9x will be enough for most scenarios. And we can use descheduling continuously to mitigate hot spot.
