### ISSUE TITLE
[BUG] Koord Scheduler Exception due to CSIStorageCapacity v1 Incompatibility

### ISSUE THREAD

**Issue by chl178** [koordinator-sh/koordinator#1784]
**What happened**:
`failed to list *v1.CSIStorageCapacity: the server could not find the requested resource`
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
k8s v1.23.13 with koordinator v1.3.0
**Anything else we need to know?**:
Under k8s v1.23.13, the output of `kubectl api-resources --api-group=storage.k8s.io`:
```
NAME                   SHORTNAMES   APIVERSION               NAMESPACED   KIND
csidrivers                          storage.k8s.io/v1        false        CSIDriver
csinodes                            storage.k8s.io/v1        false        CSINode
csistoragecapacities                storage.k8s.io/v1beta1   true         CSIStorageCapacity
storageclasses         sc           storage.k8s.io/v1        false        StorageClass
volumeattachments                   storage.k8s.io/v1        false        VolumeAttachment
```
The v1 version of CSIStorageCapacity was introduced in 1.24.
**Environment**:
- App version: v1.3.0
- Kubernetes version (use `kubectl version`): v1.23.13
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by eahydra** [comment]
Yes. koord-scheduler uses k8s scheduler framework v1.24, which uses v1.CSIStorageCapacity.
In order to be compatible with kubernetes v1.22, v1.24 and other lower versions, koord-scheduler adds feature-gate `CompatibleCSIStorageCapacity` and `DisableCSIStorageCapacityInformer`.

`CompatibleCSIStorageCapacity` will enable a custom CSIStorageCapacity informer, which will internally convert v1beta1.CSIStorageCapacity to v1.CSIStorageCapacity in memory

`DisableCSIStorageCapacityInformer` is used to disable CSIStorageCapacity informer. Versions below k8s v1.22 need to enable FeatureGate

So you can try enabling the feature gate `CompatibleCSIStorageCapacity` in koord-scheduler.
