### ISSUE TITLE
Why amplify both node allocatable CPU and CPU Request of POD?

### ISSUE THREAD

**Issue by yongming** [koordinator-sh/koordinator#1951]
According to the diagram of CPU normalization, the amplified ratio is applied on both  node allocatable CPU in node status and CPU request on scheduler filter, why design as this ?

I suppose amplified ratio only need applies on node allocatable CPU in node status. Can you please explain why CPU request amplified too?

Thanks. 

- Koordinator version: - v1.4
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by saintube** [comment]
@yongming I suppose the "CPU request amplified" you mentioned is the requests of the CPUSet pods (QoS=LSE/LSR). The CPUSet pods' requests are amplified because the current CPU normalization does not support these kinds of pods. The non-CPUSet pods (i.e. CPUShare pods) can scale their real CPU requests/limits by adjusting the CPU slices (i.e. cfs_quota and shares), while scaling the CPUSet pods' requests/limits is not easy since the granularity is the logical core. e.g. When the normalized ratio is 1.2, a CPUSet pod requesting 1 normalized core is hard to allocate 0.83 real core.

**Comment by yongming** [comment]
Got it，thanks very much!
