### ISSUE TITLE
[BUG] unexpected CPU eviction

### ISSUE THREAD

**Issue by j4ckstraw** [koordinator-sh/koordinator#2118]
**What happened**:

unexpected CPU eviction with `evictByAllocatable` cpuEvictPolicy policy

meanwhile we observed batch allocatable reach zero.
metric: `koordlet_node_resource_allocatable{resource=~"kubernetes.io/batch-cpu",node="$node"}/1000`
![image](https://github.com/koordinator-sh/koordinator/assets/18480426/fc686d49-098e-4f32-982f-d32eba69381a)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

batch resource calculate logic:
currently:
`nodeSafetyMargin = capacity * ratio` [link](https://github.com/koordinator-sh/koordinator/blob/main/pkg/slo-controller/noderesource/plugins/batchresource/util.go#L204-L213)

`batchAllocatable = capacity - nodeSafetyMargin - systemUsed - podHPUsed` [link](https://github.com/koordinator-sh/koordinator/blob/main/pkg/slo-controller/noderesource/plugins/batchresource/util.go#L43)

what I expected:
`batchAllocatable = min(capacity - systemUsed - podHPUsed, nodeSafetyMargin)`

nodeSafetyMargin should be a maximum threshold.

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
@j4ckstraw It seems to be two individual issues:
1. The batch resource fluctuation problem may cause unexpected evictions when evictPolicy=`evictByAllocatble`, which has a remaining issue and solution in #1906.
2. The question about the nodeSafetyMargin parameter. This is by design where we always reserve a ratio of node allocatable for the high-priority except their usage. Regardless, I think adding a parameter to limit the upper ratio of the batch resources is reasonable. So it is welcome to contribute this enhancement :)
